### ISSUE TITLE
Error when calculating alpha difference using cal_diff()

### ISSUE THREAD

**Issue by finally-jay** [ChiLiubio/microeco#264] opened 2023-08-02 13:35 UTC
Dear Chi

Error in data.frame(res_list$comnames, res_list$measure_use, res_list$test_method, :
arguments imply differing number of rows: 8, 7

I got this error when running the second line:

> t1 <- trans_alpha$new(dataset = meco_dataset, group = "Group")

> t1$cal_diff(method = "KW")

Could you please help me with this ?

Thank you in advance !
Jay

**Comment by ChiLiubio** [comment] 2023-08-03 05:53
Hi
I can not determine how it happened. Could you please send me you `meco_dataset` object to reproduce it? To save you meco_dataset, please use the steps in the tutorial (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) and attach the compressed object. 
Thanks.

Chi

**Comment by finally-jay** [comment] 2023-08-03 10:25
Hi Chi

I would love to send you the data, but this is a confidential dataset, I'm not allowed to send it publicly, so May I ask for your email address so that I can send it to you privately ?

I won't trouble you a lot afterwards through email, I will still comment in the github if I have any issues later.

This is my email address jiejiang_finally@163.com  , if you please write me a simple text so that I know your email address.

Thanks a lot !
Jay

**Comment by ChiLiubio** [comment] 2023-08-04 01:22
Hi Jay,

My email is liuchi0426@126.com

Chi

**Comment by ChiLiubio** [comment] 2023-08-04 12:30
Hi,

1. The issue comes from the occurrence of NAN in certain samples of the ACE metric, resulting in errors during subsequent group comparisons. Temporarily, this can be resolved by filtering diversity metrics.
```
t1$cal_diff(method = "KW", measure = c("Chao1", "Shannon"))
```
2. The negative values here are not actual negatives; rather, when there are only two groups in lefse, they are simply placed on opposite sides for visualization convenience. This is a commonly used practice in the papers as well. To verify the true positive and negative values, you can refer to the result file, i.e. LDA column in `t1$res_diff`.
```
View(t1$res_diff)
```
3. I suspect that this is related to the network structure. Please attach your steps involved in constructing the network for me to reproduce your results and find out the reason.

Best,
Chi

**Closed** 2023-11-03 01:37 UTC
